spring:
  application:
    name: white
#  会被java中的配置覆盖覆盖
  security:
    user:
      name: user
      password: 123
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootroot}
  jpa:
    database: mysql
#    database-platform: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization:

server:
  port: 8020